export const teamMeta = {
  CAN: { tr: 'Kanada', flag: 'ca' },
  MEX: { tr: 'Meksika', flag: 'mx' },
  USA: { tr: 'ABD', flag: 'us' },
  ARG: { tr: 'Arjantin', flag: 'ar' },
  BRA: { tr: 'Brezilya', flag: 'br' },
  URU: { tr: 'Uruguay', flag: 'uy' },
  COL: { tr: 'Kolombiya', flag: 'co' },
  ECU: { tr: 'Ekvador', flag: 'ec' },
  PAR: { tr: 'Paraguay', flag: 'py' },
  PER: { tr: 'Peru', flag: 'pe' },
  CHI: { tr: 'Şili', flag: 'cl' },
  FRA: { tr: 'Fransa', flag: 'fr' },
  ENG: { tr: 'İngiltere', flag: 'gb-eng' },
  SCO: { tr: 'İskoçya', flag: 'gb-sct' },
  WAL: { tr: 'Galler', flag: 'gb-wls' },
  ESP: { tr: 'İspanya', flag: 'es' },
  GER: { tr: 'Almanya', flag: 'de' },
  POR: { tr: 'Portekiz', flag: 'pt' },
  NED: { tr: 'Hollanda', flag: 'nl' },
  BEL: { tr: 'Belçika', flag: 'be' },
  ITA: { tr: 'İtalya', flag: 'it' },
  CRO: { tr: 'Hırvatistan', flag: 'hr' },
  SUI: { tr: 'İsviçre', flag: 'ch' },
  DEN: { tr: 'Danimarka', flag: 'dk' },
  POL: { tr: 'Polonya', flag: 'pl' },
  SRB: { tr: 'Sırbistan', flag: 'rs' },
  AUT: { tr: 'Avusturya', flag: 'at' },
  TUR: { tr: 'Türkiye', flag: 'tr' },
  UKR: { tr: 'Ukrayna', flag: 'ua' },
  CZE: { tr: 'Çekya', flag: 'cz' },
  NOR: { tr: 'Norveç', flag: 'no' },
  SWE: { tr: 'İsveç', flag: 'se' },
  JPN: { tr: 'Japonya', flag: 'jp' },
  KOR: { tr: 'Güney Kore', flag: 'kr' },
  AUS: { tr: 'Avustralya', flag: 'au' },
  IRN: { tr: 'İran', flag: 'ir' },
  KSA: { tr: 'Suudi Arabistan', flag: 'sa' },
  QAT: { tr: 'Katar', flag: 'qa' },
  UZB: { tr: 'Özbekistan', flag: 'uz' },
  JOR: { tr: 'Ürdün', flag: 'jo' },
  MAR: { tr: 'Fas', flag: 'ma' },
  SEN: { tr: 'Senegal', flag: 'sn' },
  TUN: { tr: 'Tunus', flag: 'tn' },
  ALG: { tr: 'Cezayir', flag: 'dz' },
  EGY: { tr: 'Mısır', flag: 'eg' },
  NGA: { tr: 'Nijerya', flag: 'ng' },
  GHA: { tr: 'Gana', flag: 'gh' },
  CMR: { tr: 'Kamerun', flag: 'cm' },
  CIV: { tr: 'Fildişi Sahili', flag: 'ci' },
  RSA: { tr: 'Güney Afrika', flag: 'za' },
  CRC: { tr: 'Kosta Rika', flag: 'cr' },
  PAN: { tr: 'Panama', flag: 'pa' },
  JAM: { tr: 'Jamaika', flag: 'jm' },
  HON: { tr: 'Honduras', flag: 'hn' },
  NZL: { tr: 'Yeni Zelanda', flag: 'nz' },
};
